backend:
  name: git-gateway
  repo: mtlgreen/mtlgreen.com
  branch: master 

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: 'events'
    label: 'Events' 
    folder: 'src/pages/events' 
    create: true 
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' 
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Start Time', name: 'startTime', widget: 'datetime' }
      - { label: 'End Time', name: 'endTime', widget: 'datetime' }
      - {
          label: 'Short Description',
          name: 'shortDescription',
          widget: 'string',
        }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Additional Images',
          name: 'images',
          widget: 'list',
          field: { label: 'Image', name: 'image', widget: 'image' }
        }
      - label: 'Address'
        name: 'address'
        widget: 'object'
        fields:
            - {
              label: 'Street and Number',
              name: 'addressDetailLevel',
              widget: 'string',
            }
            - { label: 'City', name: 'addressCityLevel', widget: 'string' }
            - { label: 'Postal Code', name: 'addressPostalCode', widget: 'string' }
      - { label: 'Ticket Price', name: 'price', widget: 'number' }
      - { label: 'Eventbrite Link', name: 'linkEventbrite', widget: 'string' }
      - { label: 'Facebook Link', name: 'linkFacebook', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'green-thoughts'
    label: 'Green Thoughts Articles' 
    folder: 'src/pages/green-thoughts' 
    create: true 
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' 
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Additional Images',
          name: 'images',
          widget: 'list',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'Author Name', name: 'authorName', widget: 'string' }
      - { label: 'Author Image', name: 'authorImage', widget: 'image' }
      - {
          label: 'Short Description',
          name: 'shortDescription',
          widget: 'string',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }