backend:
  name: git-gateway
  repo: mtlgreen/mtlgreen.com
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: static/images
public_folder: /images

collections:
  - name: 'events' # Used in routes, e.g., /admin/collections/blog
    label: 'Events' # Used in the UI
    folder: 'src/pages/events' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Start Time', name: 'startTime', widget: 'datetime' }
      - { label: 'End Time', name: 'endTime', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Additional Images',
          name: 'images',
          widget: 'list',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - label: 'Address'
        name: 'address'
        widget: 'object'
        fields:
            - {
              label: 'Street and Number',
              name: 'addressDetailLevel',
              widget: 'string',
            }
            - { label: 'City', name: 'addressCityLevel', widget: 'string' }
            - { label: 'Postal Code', name: 'addressPostalCode', widget: 'string' }
      - { label: 'Ticket Price', name: 'price', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'green-thoughts' # Used in routes, e.g., /admin/collections/blog
    label: 'Green Thoughts Articles' # Used in the UI
    folder: 'src/pages/green-thoughts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Additional Images',
          name: 'images',
          widget: 'list',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'Author Name', name: 'authorName', widget: 'string' }
      - {
          label: 'Short Description',
          name: 'shortDescription',
          widget: 'string',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }